### ISSUE TITLE
Failed Image Import

### ISSUE THREAD

**Issue by grl-sage** [Esri/raster2gpkg#2]
I run the tool with a PNG image that I exported in ArcGIS Desktop and get the error:

Traceback (most recent call last):
  File "D:\SAGE\ToolBox\raster2gpkg-masterNew\raster2gpkg-master\GeoPackageToolbox.tbx#RasterToGeoPackage.py", line 473, in <module>
  File "D:\SAGE\ToolBox\raster2gpkg-masterNew\raster2gpkg-master\GeoPackageToolbox.tbx#RasterToGeoPackage.py", line 460, in main
  File "D:\SAGE\ToolBox\raster2gpkg-masterNew\raster2gpkg-master\GeoPackageToolbox.tbx#RasterToGeoPackage.py", line 197, in add_dataset
  File "c:\arcgis\desktop10.3\arcpy\arcpy\management.py", line 15722, in ManageTileCache
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 001519: Minimum Cached Scale cannot be smaller than Maximum Cached Scale
ERROR 001520: Maximum Cached Scale cannot be greater than Minimum Cached Scale
Failed to execute (ManageTileCache).

**Comment by grl-sage** [comment]
Tried it again with the sample image packaged with the tool and it never finished running.  I had to kill the ArcMap process as Cancel did not stop the tool.

**Comment by grl-sage** [comment]
Tried another raster and received the message:

Traceback (most recent call last):
  File "D:\SAGE\ToolBox\raster2gpkg-masterNew\raster2gpkg-master\GeoPackageToolbox.tbx#RasterToGeoPackage.py", line 473, in <module>
  File "D:\SAGE\ToolBox\raster2gpkg-masterNew\raster2gpkg-master\GeoPackageToolbox.tbx#RasterToGeoPackage.py", line 460, in main
  File "D:\SAGE\ToolBox\raster2gpkg-masterNew\raster2gpkg-master\GeoPackageToolbox.tbx#RasterToGeoPackage.py", line 197, in add_dataset
  File "c:\arcgis\desktop10.3\arcpy\arcpy\management.py", line 15722, in ManageTileCache
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000800: The value is not a member of 591657527.591555 | 295828763.795777 | 147914381.897889 | 73957190.948944 | 36978595.474472 | 18489297.737236 | 9244648.868618 | 4622324.434309 | 2311162.217155 | 1155581.108577 | 577790.554289 | 288895.277144 | 144447.638572 | 72223.819286 | 36111.909643 | 18055.954822 | 9027.977411 | 4513.988705 | 2256.994353 | 1128.497176.
Failed to execute (ManageTileCache).

**Comment by lshipman** [comment]
Are you using ArcGIS 10.3 or 10.3.1. The path names you posted include 10.3, but that would be the same for either install. I need this to set up my test environment.

**Comment by grl-sage** [comment]
10.3.1
